/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline.system;


import javax.swing.JOptionPane;
import java.awt.EventQueue;


import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.logging.Level;
import javax.swing.*;
import java.lang.*;
import java.util.regex.*;

/**
 *
 * @author BHAVESH
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
        autoId();
    }
    Connection con;
    PreparedStatement pstmt;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldMob = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldAadhar = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonBook = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPassport = new javax.swing.JTextField();
        lblPassport = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAadhar = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblMob = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\AddFlight.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("Add Customer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 30, 410, 80);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Customer ID                     :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 140, 270, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("Customer Name                :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 200, 280, 40);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("Customer Mob_No            :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 260, 270, 40);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setText("Customer Address            :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 320, 270, 40);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("Passport  No                     :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 440, 270, 40);

        jTextFieldId.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldId.setEnabled(false);
        getContentPane().add(jTextFieldId);
        jTextFieldId.setBounds(400, 150, 210, 30);

        jTextFieldMob.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldMob.setMaximumSize(new java.awt.Dimension(10, 10));
        jTextFieldMob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldMobMouseReleased(evt);
            }
        });
        jTextFieldMob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMobKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMobKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldMob);
        jTextFieldMob.setBounds(400, 270, 210, 30);

        jTextFieldAddress.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldAddressMouseReleased(evt);
            }
        });
        jTextFieldAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAddressKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldAddress);
        jTextFieldAddress.setBounds(400, 330, 210, 30);

        jTextFieldAadhar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldAadhar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldAadharMouseReleased(evt);
            }
        });
        jTextFieldAadhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAadharKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldAadhar);
        jTextFieldAadhar.setBounds(400, 390, 210, 30);

        jTextFieldName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldName);
        jTextFieldName.setBounds(400, 210, 210, 30);

        jButtonCancel.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jButtonCancel.setText("CANCEL");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jButtonCancel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonCancelPropertyChange(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(390, 530, 310, 60);

        jButtonBook.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jButtonBook.setText("BOOK TICKET");
        jButtonBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });
        jButtonBook.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonBookPropertyChange(evt);
            }
        });
        getContentPane().add(jButtonBook);
        jButtonBook.setBounds(30, 530, 310, 60);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setText("Customer Aadhar No        :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 380, 270, 40);

        jTextFieldPassport.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldPassport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldPassportMouseReleased(evt);
            }
        });
        jTextFieldPassport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPassportKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPassport);
        jTextFieldPassport.setBounds(400, 450, 210, 30);

        lblPassport.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblPassport);
        lblPassport.setBounds(630, 450, 260, 16);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblName);
        lblName.setBounds(620, 210, 260, 16);

        lblAadhar.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblAadhar);
        lblAadhar.setBounds(620, 390, 260, 16);

        lblAddress.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblAddress);
        lblAddress.setBounds(630, 330, 260, 16);

        lblMob.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblMob);
        lblMob.setBounds(620, 270, 260, 16);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\MainPage.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, -100, 1720, 910);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

   
    


    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
              //System.exit(0);    
              EmployeeMenu1 a= new EmployeeMenu1();
              a.setVisible(true);            
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonCancelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonCancelPropertyChange
        jButtonCancel.setOpaque(false);
        jButtonCancel.setContentAreaFilled(false);
        
    }//GEN-LAST:event_jButtonCancelPropertyChange

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
         if(jTextFieldName.getText().trim().isEmpty())
        {
              JOptionPane.showMessageDialog(null,"Please enter Name");
        }
        try
      {
               Class.forName("com.mysql.jdbc.Driver");  
               Connection conn = DriverManager.getConnection("jdbc:mysql:///ams","root","");  

               String sql="insert into customer values(?, ?, ?, ?, ?, ?)";
               PreparedStatement pstmt=conn.prepareStatement(sql);
                pstmt.setInt(1,Integer.parseInt(jTextFieldId.getText()));
                pstmt.setString(2,jTextFieldName.getText());
                pstmt.setString(3,jTextFieldMob.getText());
               pstmt.setString(4,jTextFieldAddress.getText());
               pstmt.setString(5,jTextFieldAadhar.getText());
               pstmt.setString(6,jTextFieldPassport.getText());
               
 
              pstmt.executeUpdate();
              //JOptionPane.showMessageDialog(null,"Data Successfully Inserted in Table");
               
              conn.close();
      }
      catch(Exception e)
     {
           JOptionPane.showMessageDialog(null,e);
      }

        BookTicket a= new BookTicket();
        a.setVisible(true);
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void jButtonBookPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonBookPropertyChange
        jButtonBook.setOpaque(false);
        jButtonBook.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonBookPropertyChange

//Validation for Name 
    private void jTextFieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyPressed
       char c= evt.getKeyChar();
       if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
       {
                  jTextFieldName.setEditable(true);
       }
       else
       {
                  jTextFieldName.setEditable(false);
       }
    }//GEN-LAST:event_jTextFieldNameKeyPressed

    private void jTextFieldMobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMobKeyReleased
       
    }//GEN-LAST:event_jTextFieldMobKeyReleased
//Validation for Mobile No
    private void jTextFieldMobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMobKeyPressed
       String mob=jTextFieldMob.getText();
        int length=mob.length();
        char c=evt.getKeyChar();

       if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
       {
            if(length<10)
            {
                jTextFieldMob.setEditable(true);
            }
            else
            {
                jTextFieldMob.setEditable(false);
            }
       }
       else
       {    //allow backspace 
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                   jTextFieldMob.setEditable(true);
            }
            else
            {
                   jTextFieldMob.setEditable(false);
            }
       }
 
    }//GEN-LAST:event_jTextFieldMobKeyPressed
//validation for Address
    private void jTextFieldAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddressKeyPressed
        char c= evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        
        {
               jTextFieldAddress.setEditable(true);
            //JOptionPane.showMessageDialog(null, "Please enter only character ");
        }
        else
        {
             jTextFieldAddress.setEditable(false);
        }
    }//GEN-LAST:event_jTextFieldAddressKeyPressed
//Validation for Aadhar Card No
    private void jTextFieldAadharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAadharKeyPressed
        char c=evt.getKeyChar();
        String Aadhar=jTextFieldAadhar.getText();
        int length=Aadhar.length();
        
       if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'|| (Character.isWhitespace(c)))
       {
            if(length<14)//14 = 12 digits for aadhar card no + 2 space
            {
                jTextFieldAadhar.setEditable(true);
            }
            else
            {
                jTextFieldAadhar.setEditable(false);
            }
       }
       else
       {    //allow backspace 
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                   jTextFieldAadhar.setEditable(true);
            }
            else
            {
                   jTextFieldAadhar.setEditable(false);
            }
       }
    }//GEN-LAST:event_jTextFieldAadharKeyPressed
// Validation for pasport No
    private void jTextFieldPassportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPassportKeyPressed
       char c=evt.getKeyChar();
        String Passport=jTextFieldPassport.getText();
        int length=Passport.length();
        
       if(Character.isLetter(c)||evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
       {
           if(length<8)
           {
                jTextFieldPassport.setEditable(true);
           } 
           else
           {
                jTextFieldPassport.setEditable(false);
           }
       }
       else
       {    //allow backspace 
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                   jTextFieldPassport.setEditable(true);
            }
            else
            {
                   jTextFieldPassport.setEditable(false);
            }
       }
    }//GEN-LAST:event_jTextFieldPassportKeyPressed

    private void jTextFieldMobMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMobMouseReleased
      if(jTextFieldName.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter Name");
        }
      
    }//GEN-LAST:event_jTextFieldMobMouseReleased

    private void jTextFieldAddressMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAddressMouseReleased
       
        if(jTextFieldMob.getText().trim().isEmpty())
        {
              JOptionPane.showMessageDialog(null,"Please enter Mobile Number");
        }
    }//GEN-LAST:event_jTextFieldAddressMouseReleased

    private void jTextFieldAadharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAadharMouseReleased
        if(jTextFieldAddress.getText().trim().isEmpty())
        {
              JOptionPane.showMessageDialog(null,"Please enter Address");
        }
    }//GEN-LAST:event_jTextFieldAadharMouseReleased

    private void jTextFieldPassportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPassportMouseReleased
        if(jTextFieldAadhar.getText().trim().isEmpty())
        {
              JOptionPane.showMessageDialog(null,"Please enter Aadhar Number");
        }
    }//GEN-LAST:event_jTextFieldPassportMouseReleased

private void autoId() 
{ 
       try 
       {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql:///ams","root",""); 

             String sql="SELECT Customer_ID FROM customer ORDER BY Customer_ID DESC LIMIT 1";
             PreparedStatement pst=con.prepareStatement(sql); 
             ResultSet rs=pst.executeQuery(); 
             if(rs.next()) 
             { 
                 String bid=rs.getString("Customer_ID"); 
                 int n=Integer.parseInt(bid); 
                 n++;
                 String snum=Integer.toString(n);
                 jTextFieldId.setText(snum); 
             }
             else 
            {
                jTextFieldId.setText("1"); 
            } 
       } 
      catch (Exception e)
       { 
            JOptionPane.showMessageDialog(null, e);
       }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBook;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jTextFieldAadhar;
    public static javax.swing.JTextField jTextFieldAddress;
    public static javax.swing.JTextField jTextFieldId;
    public static javax.swing.JTextField jTextFieldMob;
    public static javax.swing.JTextField jTextFieldName;
    public static javax.swing.JTextField jTextFieldPassport;
    private javax.swing.JLabel lblAadhar;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblMob;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassport;
    // End of variables declaration//GEN-END:variables
}
