/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package airline.system;


import javax.swing.JOptionPane;
import java.awt.EventQueue;


import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author BHAVESH
 */
public class AddFlight extends javax.swing.JFrame {

    /** Creates new form AddFlight */
    public AddFlight() {
        initComponents();
        autoId();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldFare = new javax.swing.JTextField();
        jTextFieldDestination = new javax.swing.JTextField();
        jTextFieldSource = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD FLIGHT DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 60, 583, 60);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fare               :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 390, 210, 40);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Flight No       :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 160, 210, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Flight Name  :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 220, 210, 40);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Source           :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 280, 210, 40);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Destination   :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 340, 210, 40);

        jButtonCancel.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("CANCEL");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jButtonCancel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonCancelPropertyChange(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(640, 560, 250, 70);

        jButtonAdd.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("ADD DETAILS");
        jButtonAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jButtonAdd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonAddPropertyChange(evt);
            }
        });
        getContentPane().add(jButtonAdd);
        jButtonAdd.setBounds(100, 560, 440, 70);

        jTextFieldFare.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldFare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldFareMouseReleased(evt);
            }
        });
        jTextFieldFare.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFareKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldFare);
        jTextFieldFare.setBounds(510, 400, 240, 30);

        jTextFieldDestination.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldDestination.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldDestinationMouseReleased(evt);
            }
        });
        jTextFieldDestination.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDestinationKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldDestination);
        jTextFieldDestination.setBounds(510, 350, 240, 30);

        jTextFieldSource.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldSource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextFieldSourceMouseReleased(evt);
            }
        });
        jTextFieldSource.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSourceKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldSource);
        jTextFieldSource.setBounds(510, 290, 240, 30);

        jTextFieldName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldName);
        jTextFieldName.setBounds(510, 230, 240, 30);

        jTextFieldNo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldNo.setEnabled(false);
        getContentPane().add(jTextFieldNo);
        jTextFieldNo.setBounds(510, 170, 240, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\AddFlight.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -60, 1490, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if(jTextFieldFare.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter Fare","swing Tester",JOptionPane.WARNING_MESSAGE);
        }
        
        try
      {
               Class.forName("com.mysql.jdbc.Driver");  
               Connection conn = DriverManager.getConnection("jdbc:mysql:///ams","root","");  

               String sql="insert into flight values(?, ?, ?, ?, ?)";
               PreparedStatement pstmt=conn.prepareStatement(sql);
                pstmt.setInt(1,Integer.parseInt(jTextFieldNo.getText()));
                pstmt.setString(2,jTextFieldName.getText());
                pstmt.setString(3,jTextFieldSource.getText());
               pstmt.setString(4,jTextFieldDestination.getText());
               pstmt.setString(5,jTextFieldFare.getText());
              

              pstmt.executeUpdate();
              JOptionPane.showMessageDialog(null,"Data Successfully Inserted in Table");
              conn.close();
      }
      catch(Exception e)
     {
           JOptionPane.showMessageDialog(null,e);
      }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed

       AdminMenu1 a=new AdminMenu1();
        a.setVisible(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAddPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonAddPropertyChange
        jButtonAdd.setOpaque(false);
        jButtonAdd.setContentAreaFilled(false);
      
    }//GEN-LAST:event_jButtonAddPropertyChange

    private void jButtonCancelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonCancelPropertyChange
        jButtonCancel.setOpaque(false);
        jButtonCancel.setContentAreaFilled(false);
        
    }//GEN-LAST:event_jButtonCancelPropertyChange
//Validation for Name
    private void jTextFieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyPressed
        char c= evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
               jTextFieldName.setEditable(true);
        }
        else
        {
             jTextFieldName.setEditable(false);
        }
    }//GEN-LAST:event_jTextFieldNameKeyPressed
//Validation for Source
    private void jTextFieldSourceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSourceKeyPressed
         char c= evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
               jTextFieldSource.setEditable(true);
        }
        else
        {
             jTextFieldSource.setEditable(false);
        }
    }//GEN-LAST:event_jTextFieldSourceKeyPressed
//Validation for Destination
    private void jTextFieldDestinationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDestinationKeyPressed
        char c= evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
               jTextFieldDestination.setEditable(true);
        }
        else
        {
             jTextFieldDestination.setEditable(false);
        }
    }//GEN-LAST:event_jTextFieldDestinationKeyPressed
//Validation for Fare
    private void jTextFieldFareKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFareKeyPressed
        String age=jTextFieldFare.getText();
        int length=age.length();
        char c=evt.getKeyChar();

       if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
       {
            if(length<7)
            {
                jTextFieldFare.setEditable(true);
            }
            else
            {
                jTextFieldFare.setEditable(false);
            }
       }
       else
       {    //allow backspace 
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                   jTextFieldFare.setEditable(true);
            }
            else
            {
                   jTextFieldFare.setEditable(false);
            }
       } 
    }//GEN-LAST:event_jTextFieldFareKeyPressed

    private void jTextFieldSourceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSourceMouseReleased
         if(jTextFieldName.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter Flight Name","swing Tester",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldSourceMouseReleased

    private void jTextFieldDestinationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDestinationMouseReleased
        if(jTextFieldSource.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter Source","swing Tester",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldDestinationMouseReleased

    private void jTextFieldFareMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFareMouseReleased
         if(jTextFieldDestination.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter Destination","swing Tester",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldFareMouseReleased
private void autoId() 
{ 
       try 
       {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql:///ams","root",""); 

             String sql="SELECT Flight_No FROM flight ORDER BY Flight_No DESC LIMIT 1";
             PreparedStatement pst=con.prepareStatement(sql); 
             ResultSet rs=pst.executeQuery(); 
             if(rs.next()) 
             { 
                 String bid=rs.getString("Flight_No"); 
                 int n=Integer.parseInt(bid); 
                 n++;
                 String snum=Integer.toString(n);
                 jTextFieldNo.setText(snum); 
             }
             else 
            {
                jTextFieldNo.setText("1"); 
            } 
       } 
      catch (Exception e)
       { 
            JOptionPane.showMessageDialog(null, e);
       }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JTextField jTextFieldDestination;
    public static javax.swing.JTextField jTextFieldFare;
    public static javax.swing.JTextField jTextFieldName;
    public static javax.swing.JTextField jTextFieldNo;
    public static javax.swing.JTextField jTextFieldSource;
    // End of variables declaration//GEN-END:variables

}
