/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package airline.system;

/**
 *
 * @author BHAVESH
 */
public class AdminMenu1 extends javax.swing.JFrame {

    /** Creates new form AdminMenu1 */
    public AdminMenu1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        AddFlight = new javax.swing.JMenuItem();
        RemoveFlight = new javax.swing.JMenuItem();
        ViewFlight = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AddEmployee = new javax.swing.JMenuItem();
        RemoveEmployee = new javax.swing.JMenuItem();
        ViewEmployee = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ViewCustomer = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        FlightReport = new javax.swing.JMenuItem();
        EmployeeReport = new javax.swing.JMenuItem();
        CustomerReport = new javax.swing.JMenuItem();
        TicketBookingReport = new javax.swing.JMenuItem();
        PaymentReport = new javax.swing.JMenuItem();
        CancellationReport = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        jButtonBack.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButtonBack.setText("BACK");
        jButtonBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jButtonBack.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonBackPropertyChange(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(1180, 580, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\Image1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -130, 1460, 990);

        jMenu2.setText("Flight");

        AddFlight.setText("Add Flight");
        AddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightActionPerformed(evt);
            }
        });
        jMenu2.add(AddFlight);

        RemoveFlight.setText("Remove Flight");
        RemoveFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveFlightActionPerformed(evt);
            }
        });
        jMenu2.add(RemoveFlight);

        ViewFlight.setText("View Flights");
        ViewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewFlightActionPerformed(evt);
            }
        });
        jMenu2.add(ViewFlight);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Employee");

        AddEmployee.setText("Add Employee");
        AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeActionPerformed(evt);
            }
        });
        jMenu3.add(AddEmployee);

        RemoveEmployee.setText("Remove Employee");
        RemoveEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmployeeActionPerformed(evt);
            }
        });
        jMenu3.add(RemoveEmployee);

        ViewEmployee.setText("View Employee");
        ViewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmployeeActionPerformed(evt);
            }
        });
        jMenu3.add(ViewEmployee);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Customer");

        ViewCustomer.setText("View Customer");
        ViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCustomerActionPerformed(evt);
            }
        });
        jMenu4.add(ViewCustomer);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reports");

        FlightReport.setText("Flight Report");
        FlightReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightReportActionPerformed(evt);
            }
        });
        jMenu5.add(FlightReport);

        EmployeeReport.setText("Employee Report");
        EmployeeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeReportActionPerformed(evt);
            }
        });
        jMenu5.add(EmployeeReport);

        CustomerReport.setText("Customer Report");
        CustomerReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerReportActionPerformed(evt);
            }
        });
        jMenu5.add(CustomerReport);

        TicketBookingReport.setText("Ticket Booking Report");
        TicketBookingReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketBookingReportActionPerformed(evt);
            }
        });
        jMenu5.add(TicketBookingReport);

        PaymentReport.setText("Payment Report");
        PaymentReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentReportActionPerformed(evt);
            }
        });
        jMenu5.add(PaymentReport);

        CancellationReport.setText("Cancellation Report");
        CancellationReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancellationReportActionPerformed(evt);
            }
        });
        jMenu5.add(CancellationReport);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveFlightActionPerformed
        RemoveFlight b=new RemoveFlight();
        b.setVisible(true); 
    }//GEN-LAST:event_RemoveFlightActionPerformed

    private void ViewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFlightActionPerformed
        ViewFlight c=new ViewFlight();
        c.setVisible(true); 
    }//GEN-LAST:event_ViewFlightActionPerformed

    private void AddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightActionPerformed
                AddFlight a=new AddFlight();
                a.setVisible(true);        
    }//GEN-LAST:event_AddFlightActionPerformed

    private void AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeActionPerformed
        AddEmployee a=new AddEmployee();
                a.setVisible(true);        
    }//GEN-LAST:event_AddEmployeeActionPerformed

    private void RemoveEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveEmployeeActionPerformed
        RemoveEmp a=new RemoveEmp();
                a.setVisible(true);        
    }//GEN-LAST:event_RemoveEmployeeActionPerformed

    private void ViewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmployeeActionPerformed
       ViewEmployee a=new ViewEmployee();
                a.setVisible(true);        
    }//GEN-LAST:event_ViewEmployeeActionPerformed

    private void ViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCustomerActionPerformed
        ViewCustomerDetails a=new ViewCustomerDetails();
                a.setVisible(true);        
    }//GEN-LAST:event_ViewCustomerActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        MainPage a=new MainPage();
        a.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonBackPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonBackPropertyChange
       jButtonBack.setOpaque(false);
        jButtonBack.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonBackPropertyChange

    private void EmployeeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeReportActionPerformed
        EmpReports a=new EmpReports();
        a.setVisible(true);
    }//GEN-LAST:event_EmployeeReportActionPerformed

    private void FlightReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightReportActionPerformed
        FlightReport a=new FlightReport();
        a.setVisible(true);
    }//GEN-LAST:event_FlightReportActionPerformed

    private void CustomerReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerReportActionPerformed
        CustomerReport a=new CustomerReport();
        a.setVisible(true);
    }//GEN-LAST:event_CustomerReportActionPerformed

    private void TicketBookingReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketBookingReportActionPerformed
        TicketBookingReport a=new TicketBookingReport();
        a.setVisible(true);
    }//GEN-LAST:event_TicketBookingReportActionPerformed

    private void PaymentReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentReportActionPerformed
       PaymentReport a=new PaymentReport();
       a.setVisible(true);
    }//GEN-LAST:event_PaymentReportActionPerformed

    private void CancellationReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancellationReportActionPerformed
      CancellationReport a=new CancellationReport();
      a.setVisible(true);
    }//GEN-LAST:event_CancellationReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddEmployee;
    private javax.swing.JMenuItem AddFlight;
    private javax.swing.JMenuItem CancellationReport;
    private javax.swing.JMenuItem CustomerReport;
    private javax.swing.JMenuItem EmployeeReport;
    private javax.swing.JMenuItem FlightReport;
    private javax.swing.JMenuItem PaymentReport;
    private javax.swing.JMenuItem RemoveEmployee;
    private javax.swing.JMenuItem RemoveFlight;
    private javax.swing.JMenuItem TicketBookingReport;
    private javax.swing.JMenuItem ViewCustomer;
    private javax.swing.JMenuItem ViewEmployee;
    private javax.swing.JMenuItem ViewFlight;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables

}
