/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline.system;

import airline.system.AdminLogin;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
//import javax.swing.*;
//import java.sql.ResultSet;
import javax.swing.JOptionPane;
//import java.awt.*;
//import java.awt.event.*;
//import javax.swing.*;
//import java.sql.*;


/**
 *
 * @author BHAVESH
 */
public class AdminLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        //unvisible jButton open at form load
        jButtonOpen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldusername = new javax.swing.JTextField();
        jButtonreset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jButtonlogin = new javax.swing.JButton();
        jButtonOpen = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jButtoncancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 40));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("Admin Login");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 60, 270, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 170, 170, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 260, 160, 30);
        jPanel1.add(jTextFieldusername);
        jTextFieldusername.setBounds(490, 170, 160, 30);

        jButtonreset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonreset.setText("RESET");
        jButtonreset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });
        jButtonreset.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonresetPropertyChange(evt);
            }
        });
        jPanel1.add(jButtonreset);
        jButtonreset.setBounds(450, 340, 110, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\Login-removebg-preview.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 100, 200, 240);

        jPassword.setEchoChar('*');
        jPanel1.add(jPassword);
        jPassword.setBounds(490, 260, 160, 30);

        jButtonlogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonlogin.setText("LOGIN");
        jButtonlogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloginActionPerformed(evt);
            }
        });
        jButtonlogin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonloginPropertyChange(evt);
            }
        });
        jPanel1.add(jButtonlogin);
        jButtonlogin.setBounds(310, 340, 100, 50);

        jButtonOpen.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\eyeOpen.png")); // NOI18N
        jButtonOpen.setBorder(null);
        jButtonOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOpenMouseClicked(evt);
            }
        });
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });
        jButtonOpen.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonOpenPropertyChange(evt);
            }
        });
        jPanel1.add(jButtonOpen);
        jButtonOpen.setBounds(670, 260, 50, 30);

        jButtonClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\EyeClose.png")); // NOI18N
        jButtonClose.setBorder(null);
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jButtonClose.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonClosePropertyChange(evt);
            }
        });
        jPanel1.add(jButtonClose);
        jButtonClose.setBounds(670, 260, 50, 30);

        jButtoncancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtoncancel.setText("CANCEL");
        jButtoncancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelActionPerformed(evt);
            }
        });
        jButtoncancel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtoncancelPropertyChange(evt);
            }
        });
        jPanel1.add(jButtoncancel);
        jButtoncancel.setBounds(600, 340, 110, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(290, 100, 790, 456);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\Login 1.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -120, 1460, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
         jTextFieldusername.setText(null);
         jPassword.setText(null);   
          
    }//GEN-LAST:event_jButtonresetActionPerformed

    private void jButtonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloginActionPerformed
            String pass=new String(jPassword.getPassword());
            if(jTextFieldusername.getText().equals("Admin")&& pass.equals("Admin123"))
            {
                     //JOptionPane.showMessageDialog(null,"Login succesufull");
                      
                      AdminMenu1 a=new AdminMenu1();
                      a.setVisible(true);
            }
           else
           {
                    JOptionPane.showMessageDialog(null,"Invalid Login Details","Login Error",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButtonloginActionPerformed

    private void jButtonloginPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonloginPropertyChange
        jButtonlogin.setOpaque(false);
        jButtonlogin.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonloginPropertyChange

    private void jButtonresetPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonresetPropertyChange
         jButtonreset.setOpaque(false);
        jButtonreset.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonresetPropertyChange

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed
      
       
    }//GEN-LAST:event_jButtonOpenActionPerformed

    private void jButtonOpenPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonOpenPropertyChange
        jButtonOpen.setOpaque(false);
        jButtonOpen.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonOpenPropertyChange

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonClosePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonClosePropertyChange
        jButtonClose.setOpaque(false);
        jButtonClose.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonClosePropertyChange

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
       //image change at button click for password eye
        jButtonClose.setVisible(false);
        jButtonOpen.setVisible(true);
        
        //To see type character we use 0 here
         jPassword.setEchoChar((char)0);
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private void jButtonOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpenMouseClicked
        //image change at button click for password eye
        jButtonClose.setVisible(true);
        jButtonOpen.setVisible(false);
        
        //set password to *
         jPassword.setEchoChar('*');
    }//GEN-LAST:event_jButtonOpenMouseClicked

    private void jButtoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelActionPerformed
       MainPage a= new MainPage();
      a.setVisible(true);     
    }//GEN-LAST:event_jButtoncancelActionPerformed

    private void jButtoncancelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtoncancelPropertyChange
     jButtoncancel.setOpaque(false);
        jButtoncancel.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtoncancelPropertyChange
                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtoncancel;
    private javax.swing.JButton jButtonlogin;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldusername;
    // End of variables declaration//GEN-END:variables

private void systemExit()
{
      WindowEvent winCloseing= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
}






}
