/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline.system;


import static airline.system.AddCustomer.jTextFieldAadhar;
import static airline.system.AddCustomer.jTextFieldAddress;
import static airline.system.AddCustomer.jTextFieldId;
import static airline.system.AddCustomer.jTextFieldMob;
import static airline.system.AddCustomer.jTextFieldName;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.logging.Level;
import javax.swing.*;
import java.lang.*;
/**
 *
 * @author BHAVESH
 */
public class BookTicket extends javax.swing.JFrame {
        //String a=AddCustomer.jTextFieldId.getText();
      //String a=AddCustomer.jTextFieldId.getText();
      
       Connection con;


    /**
     * Creates new form BookTicket
     */
    public BookTicket() {
     
        initComponents();

       autoId();
       
       //Connection con = DriverManager.getConnection("jdbc:mysql:///ams","root",""); 
       // To get Value from AddCustomer Frame 
        
       jTextFieldCid.setText(AddCustomer.jTextFieldId.getText());
        jTextFieldCname.setText(AddCustomer.jTextFieldName.getText());
        jTextFieldCmob.setText(AddCustomer.jTextFieldMob.getText());
        jTextFieldCaddress.setText(AddCustomer.jTextFieldAddress.getText());
        jTextFieldCaadhar.setText(AddCustomer.jTextFieldAadhar.getText());
        jTextFieldPassport.setText(AddCustomer.jTextFieldPassport.getText());

        // To get Value CheckFlightDetails from  Frame 
        jTextFieldDate.setText(CheckFlightDetails.jTextFieldDate.getText());
        jTextFieldFid.setText(CheckFlightDetails.jTextFieldNo.getText());
        jTextFieldFname.setText(CheckFlightDetails.jTextFieldName.getText());
        jTextFieldFsource.setText(CheckFlightDetails.jTextFieldSource.getText());
        jTextFieldFdestination.setText(CheckFlightDetails.jTextFieldDestination.getText());
        jTextFieldFfare.setText(CheckFlightDetails.jTextFieldFare.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCaadhar = new javax.swing.JTextField();
        jTextFieldCname = new javax.swing.JTextField();
        jTextFieldCmob = new javax.swing.JTextField();
        jTextFieldCaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCid = new javax.swing.JTextField();
        jTextFieldFid = new javax.swing.JTextField();
        jTextFieldFname = new javax.swing.JTextField();
        jTextFieldFsource = new javax.swing.JTextField();
        jTextFieldFdestination = new javax.swing.JTextField();
        jButtonMakepayment = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldTicketID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldFfare = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPassport = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("BOOK TICKET");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 10, 410, 80);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setText("Flight Information");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(740, 170, 470, 50);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel3.setText("Customer Information");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 170, 470, 50);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("Journey Date       :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 570, 270, 40);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setText("Customer Name   :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 300, 230, 40);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("Mobile No             :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 360, 230, 40);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setText("Address                :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 410, 230, 40);

        jTextFieldCaadhar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldCaadhar.setEnabled(false);
        getContentPane().add(jTextFieldCaadhar);
        jTextFieldCaadhar.setBounds(350, 480, 200, 30);

        jTextFieldCname.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldCname.setEnabled(false);
        getContentPane().add(jTextFieldCname);
        jTextFieldCname.setBounds(350, 310, 200, 30);

        jTextFieldCmob.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldCmob.setEnabled(false);
        getContentPane().add(jTextFieldCmob);
        jTextFieldCmob.setBounds(350, 370, 200, 30);

        jTextFieldCaddress.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldCaddress.setEnabled(false);
        getContentPane().add(jTextFieldCaddress);
        jTextFieldCaddress.setBounds(350, 420, 200, 30);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setText("Ticket Booking ID        :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 120, 260, 40);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setText("Flight ID             :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(710, 240, 210, 40);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setText("Flight Name        :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(710, 310, 210, 40);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel12.setText("Source                 :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(710, 370, 210, 40);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel13.setText("Destination         :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(710, 420, 210, 40);

        jTextFieldCid.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldCid.setEnabled(false);
        getContentPane().add(jTextFieldCid);
        jTextFieldCid.setBounds(350, 250, 200, 30);

        jTextFieldFid.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldFid.setEnabled(false);
        getContentPane().add(jTextFieldFid);
        jTextFieldFid.setBounds(950, 250, 200, 30);

        jTextFieldFname.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldFname.setEnabled(false);
        getContentPane().add(jTextFieldFname);
        jTextFieldFname.setBounds(950, 310, 200, 30);

        jTextFieldFsource.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldFsource.setEnabled(false);
        getContentPane().add(jTextFieldFsource);
        jTextFieldFsource.setBounds(950, 370, 200, 30);

        jTextFieldFdestination.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldFdestination.setEnabled(false);
        getContentPane().add(jTextFieldFdestination);
        jTextFieldFdestination.setBounds(950, 430, 200, 30);

        jButtonMakepayment.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jButtonMakepayment.setText("MAKE PAYMENT");
        jButtonMakepayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonMakepayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakepaymentActionPerformed(evt);
            }
        });
        jButtonMakepayment.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonMakepaymentPropertyChange(evt);
            }
        });
        jButtonMakepayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonMakepaymentKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonMakepayment);
        jButtonMakepayment.setBounds(610, 550, 370, 60);

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel15.setText("Customer ID        :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(100, 250, 210, 40);

        jTextFieldTicketID.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldTicketID.setEnabled(false);
        getContentPane().add(jTextFieldTicketID);
        jTextFieldTicketID.setBounds(720, 120, 200, 30);

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel16.setText("Aadhar No            :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(100, 470, 230, 40);

        jTextFieldDate.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldDate.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldDate.setEnabled(false);
        jTextFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusLost(evt);
            }
        });
        getContentPane().add(jTextFieldDate);
        jTextFieldDate.setBounds(350, 580, 200, 30);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel14.setText("Fare                     :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(710, 480, 210, 40);

        jTextFieldFfare.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldFfare.setEnabled(false);
        getContentPane().add(jTextFieldFfare);
        jTextFieldFfare.setBounds(950, 490, 200, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("Passport No         :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 520, 270, 40);

        jTextFieldPassport.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldPassport.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldPassport.setEnabled(false);
        jTextFieldPassport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPassportFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPassportFocusLost(evt);
            }
        });
        getContentPane().add(jTextFieldPassport);
        jTextFieldPassport.setBounds(350, 530, 200, 30);

        jButtonCancel.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jButtonCancel.setText("CANCEL");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jButtonCancel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonCancelPropertyChange(evt);
            }
        });
        jButtonCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(1010, 550, 310, 60);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Desktop\\Airline-Management-System\\Icons\\mainpage.jpg")); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 1500, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMakepaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakepaymentActionPerformed
        
        // Insert record into ticketbooking and payment tables
        try
        {       //Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql:///ams","root","");

                String sql="insert into ticketbooking values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmt=con.prepareStatement(sql);
                pstmt.setInt(1,Integer.parseInt(jTextFieldTicketID.getText()));
                pstmt.setInt(2,Integer.parseInt(jTextFieldCid.getText()));
                pstmt.setString(3,jTextFieldCname.getText());
                pstmt.setString(4,jTextFieldCmob.getText());
                pstmt.setString(5,jTextFieldCaddress.getText());
                pstmt.setString(6,jTextFieldCaadhar.getText());
               // pstmt.setString(7,jTextFieldPassport.getText());
                pstmt.setString(7,jTextFieldFid.getText());
                pstmt.setString(8,jTextFieldFname.getText());
                pstmt.setString(9,jTextFieldFsource.getText());
                pstmt.setString(10,jTextFieldFdestination.getText());
                pstmt.setString(11,jTextFieldFfare.getText());
                pstmt.setString(12,jTextFieldPassport.getText());
                
                pstmt.executeUpdate();
                
                String s="insert into payment values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pst=con.prepareStatement(s);
                pst.setInt(1,Integer.parseInt(jTextFieldTicketID.getText()));
                pst.setInt(2,Integer.parseInt(jTextFieldCid.getText()));
                pst.setString(3,jTextFieldCname.getText());
                pst.setString(4,jTextFieldCmob.getText());
                pst.setString(5,jTextFieldCaddress.getText());
                pst.setString(6,jTextFieldCaadhar.getText());
                pst.setString(7,jTextFieldFid.getText());
                pst.setString(8,jTextFieldFname.getText());
                pst.setString(9,jTextFieldFsource.getText());
                pst.setString(10,jTextFieldFdestination.getText());
                pst.setString(11,jTextFieldFfare.getText());
                pst.setString(12,jTextFieldPassport.getText());
                

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Payment Done Successfully.......!!!");
        }
       catch(Exception e)
       {
                 JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButtonMakepaymentActionPerformed

    private void jTextFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusGained
        
    }//GEN-LAST:event_jTextFieldDateFocusGained

    private void jTextFieldDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusLost
        
    }//GEN-LAST:event_jTextFieldDateFocusLost

    private void jTextFieldPassportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPassportFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPassportFocusGained

    private void jTextFieldPassportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPassportFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPassportFocusLost

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        
        EmployeeMenu1 a= new EmployeeMenu1();
        a.setVisible(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonCancelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonCancelPropertyChange
        jButtonCancel.setOpaque(false);
        jButtonCancel.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonCancelPropertyChange

    private void jButtonMakepaymentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonMakepaymentKeyPressed
        
    }//GEN-LAST:event_jButtonMakepaymentKeyPressed

    private void jButtonCancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelKeyPressed
        
    }//GEN-LAST:event_jButtonCancelKeyPressed

    private void jButtonMakepaymentPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonMakepaymentPropertyChange
        jButtonMakepayment.setOpaque(false);
        jButtonMakepayment.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonMakepaymentPropertyChange

private void autoId() 
{ 
       try 
       {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql:///ams","root",""); 

             String sql="SELECT Booking_ID FROM ticketbooking ORDER BY Booking_ID DESC LIMIT 1";
             PreparedStatement pst=con.prepareStatement(sql); 
             ResultSet rs=pst.executeQuery(); 
             if(rs.next()) 
             { 
                 String bid=rs.getString("Booking_ID"); 
                 //int co=bid.length(); 
                 //String txt= bid.substring(0, 1); 
                 //String num=bid.substring(1, co); 
                 int n=Integer.parseInt(bid); 
                 n++;
                  
                 String snum=Integer.toString(n);
                 //String ftxt=txt+snum; 
                 jTextFieldTicketID.setText(snum); 
             }
             else 
            {
                jTextFieldTicketID.setText("1"); 
            } 
       } 
      catch (Exception e)
       { 
            JOptionPane.showMessageDialog(null, e);
       }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonMakepayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCaadhar;
    private javax.swing.JTextField jTextFieldCaddress;
    private javax.swing.JTextField jTextFieldCid;
    private javax.swing.JTextField jTextFieldCmob;
    private javax.swing.JTextField jTextFieldCname;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldFdestination;
    private javax.swing.JTextField jTextFieldFfare;
    private javax.swing.JTextField jTextFieldFid;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldFsource;
    private javax.swing.JTextField jTextFieldPassport;
    private javax.swing.JTextField jTextFieldTicketID;
    // End of variables declaration//GEN-END:variables
}
