
package airline.system;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
//import airline.system.AdminLogin;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
//import javax.swing.*;
//import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class EmployeeLogin extends javax.swing.JFrame {
    

    public EmployeeLogin() {
        initComponents();
        // image eye open will be hide at form load
        jButtonOpen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldusername = new javax.swing.JTextField();
        jButtoncancel = new javax.swing.JButton();
        jButtonreset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jButtonlogin = new javax.swing.JButton();
        jButtonOpen = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 40));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("EMPLOYEE LOGIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 60, 390, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 150, 100, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 210, 100, 30);
        jPanel1.add(jTextFieldusername);
        jTextFieldusername.setBounds(450, 150, 160, 30);

        jButtoncancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtoncancel.setText("CANCEL");
        jButtoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtoncancel);
        jButtoncancel.setBounds(600, 280, 110, 50);

        jButtonreset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonreset.setText("RESET");
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonreset);
        jButtonreset.setBounds(460, 280, 90, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\Login-removebg-preview.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 90, 200, 240);
        jPanel1.add(jPassword);
        jPassword.setBounds(450, 210, 160, 30);

        jButtonlogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonlogin.setText("LOGIN");
        jButtonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonlogin);
        jButtonlogin.setBounds(310, 280, 100, 50);

        jButtonOpen.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\eyeOpen.png")); // NOI18N
        jButtonOpen.setBorder(null);
        jButtonOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOpenMouseClicked(evt);
            }
        });
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });
        jButtonOpen.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonOpenPropertyChange(evt);
            }
        });
        jPanel1.add(jButtonOpen);
        jButtonOpen.setBounds(630, 210, 50, 30);

        jButtonClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\EyeClose.png")); // NOI18N
        jButtonClose.setBorder(null);
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jButtonClose.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonClosePropertyChange(evt);
            }
        });
        jPanel1.add(jButtonClose);
        jButtonClose.setBounds(630, 210, 50, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(220, 150, 810, 410);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\Login 1.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -10, 1460, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelActionPerformed
        //System.exit(0);
       MainPage a= new MainPage();
       a.setVisible(true);       
    }//GEN-LAST:event_jButtoncancelActionPerformed

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        jTextFieldusername.setText(null);
        jPassword.setText(null);

    }//GEN-LAST:event_jButtonresetActionPerformed

    private void jButtonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloginActionPerformed
        String pass=new String(jPassword.getPassword());
        if(jTextFieldusername.getText().equals("Employee")&& pass.equals("Employee123"))
        {
            //JOptionPane.showMessageDialog(null,"Login succesufull");

            EmployeeMenu1 a=new EmployeeMenu1();
            a.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid Login Details","Login Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonloginActionPerformed

    private void jButtonOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpenMouseClicked
        //image change at button click for password eye
        jButtonClose.setVisible(true);
        jButtonOpen.setVisible(false);

        //set password to *
        jPassword.setEchoChar('*');
    }//GEN-LAST:event_jButtonOpenMouseClicked

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed

    }//GEN-LAST:event_jButtonOpenActionPerformed

    private void jButtonOpenPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonOpenPropertyChange
        jButtonOpen.setOpaque(false);
        jButtonOpen.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonOpenPropertyChange

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        //image change at button click for password eye
        jButtonClose.setVisible(false);
        jButtonOpen.setVisible(true);

        //To see type character we use 0 here
        jPassword.setEchoChar((char)0);
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonClosePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonClosePropertyChange
        jButtonClose.setOpaque(false);
        jButtonClose.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonClosePropertyChange

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtoncancel;
    private javax.swing.JButton jButtonlogin;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldusername;
    // End of variables declaration//GEN-END:variables
}
