/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline.system;

/**
 *
 * @author BHAVESH
 */
public class EmployeeMenu1 extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeMenu1
     */
    public EmployeeMenu1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CheckFlight = new javax.swing.JMenuItem();
        AddCustomer = new javax.swing.JMenuItem();
        BookTicket = new javax.swing.JMenuItem();
        TicketCancellation = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        jButtonBack.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButtonBack.setText("BACK");
        jButtonBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jButtonBack.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonBackPropertyChange(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(1200, 570, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\Image1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -130, 1500, 1020);

        jMenu1.setText("Menus");

        CheckFlight.setText("Check Flight");
        CheckFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckFlightActionPerformed(evt);
            }
        });
        jMenu1.add(CheckFlight);

        AddCustomer.setText("Add Customer");
        AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerActionPerformed(evt);
            }
        });
        jMenu1.add(AddCustomer);

        BookTicket.setText("Book Ticket");
        BookTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTicketActionPerformed(evt);
            }
        });
        jMenu1.add(BookTicket);

        TicketCancellation.setText("Ticket Cancellation");
        TicketCancellation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketCancellationActionPerformed(evt);
            }
        });
        jMenu1.add(TicketCancellation);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckFlightActionPerformed
        CheckFlightDetails a=new CheckFlightDetails();
         a.setVisible(true);
    }//GEN-LAST:event_CheckFlightActionPerformed

    private void AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerActionPerformed
        AddCustomer a=new AddCustomer();
        a.setVisible(true);
    }//GEN-LAST:event_AddCustomerActionPerformed

    private void BookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTicketActionPerformed
        BookTicket a=new BookTicket();
        a.setVisible(true);
    }//GEN-LAST:event_BookTicketActionPerformed

    private void TicketCancellationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketCancellationActionPerformed
        TicketCancellation a=new TicketCancellation();
        a.setVisible(true);
    }//GEN-LAST:event_TicketCancellationActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        MainPage a=new MainPage();
        a.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonBackPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonBackPropertyChange
        jButtonBack.setOpaque(false);
        jButtonBack.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonBackPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeMenu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddCustomer;
    private javax.swing.JMenuItem BookTicket;
    private javax.swing.JMenuItem CheckFlight;
    private javax.swing.JMenuItem TicketCancellation;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
