/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Atharv
 */
public class RemoveEmp extends javax.swing.JFrame {

    /**
     * Creates new form RemoveEmp
     */
    public RemoveEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("REMOVE EMPLOYEE DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 70, 790, 60);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setText("Enter Employee Name to Search :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 260, 460, 50);

        jTextFieldSearch.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldSearch);
        jTextFieldSearch.setBounds(100, 344, 199, 30);

        jButtonSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\Search-removebg-preview (3).png")); // NOI18N
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jButtonSearch.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonSearchPropertyChange(evt);
            }
        });
        getContentPane().add(jButtonSearch);
        jButtonSearch.setBounds(340, 330, 60, 60);

        jButtonRemove.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jButtonRemove.setText("REMOVE");
        jButtonRemove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });
        jButtonRemove.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonRemovePropertyChange(evt);
            }
        });
        getContentPane().add(jButtonRemove);
        jButtonRemove.setBounds(40, 450, 148, 35);

        jButtonCancel.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jButtonCancel.setText("CANCEL");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jButtonCancel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonCancelPropertyChange(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(280, 450, 148, 35);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\FlightMenu.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -130, 1530, 970);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased

    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed

         if(jTextFieldSearch.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter Employee Name","swing Tester",JOptionPane.WARNING_MESSAGE);
        }
        
        Function f=new Function();
        ResultSet rs=null;
       

        rs=f.find(jTextFieldSearch.getText());
        try
        {
            if(rs.next())
            {
                //jTextFieldD.setText(rs.getString("Source"));
                JOptionPane.showMessageDialog(null, "Data Found");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Data Not Found");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonSearchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonSearchPropertyChange
        jButtonSearch.setOpaque(false);
        jButtonSearch.setContentAreaFilled(false);
        jButtonSearch.setBorderPainted(false);
    }//GEN-LAST:event_jButtonSearchPropertyChange

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        Connection con=null;
        ResultSet rs=null;
        PreparedStatement ps=null;

        int p=JOptionPane.showConfirmDialog(null, "Do you really want to delete","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){

            String sql="delete from employee where Employee_Name=?";
            try{
                con = DriverManager.getConnection("jdbc:mysql:///ams","root","");
                ps=con.prepareStatement(sql);
                ps.setString(1,jTextFieldSearch.getText());
                ps.execute();
                JOptionPane.showMessageDialog(null, "Record Deleted Successfully");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
            //Update_table();
        }
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonRemovePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonRemovePropertyChange
        jButtonRemove.setOpaque(false);
        jButtonRemove.setContentAreaFilled(false);
        
    }//GEN-LAST:event_jButtonRemovePropertyChange

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        //System.exit(0);
        AdminMenu1 a= new AdminMenu1();
              a.setVisible(true);       
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonCancelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonCancelPropertyChange
        jButtonCancel.setOpaque(false);
        jButtonCancel.setContentAreaFilled(false);

    }//GEN-LAST:event_jButtonCancelPropertyChange
//Validation for Emp Name Search
    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
         char c= evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
               jTextFieldSearch.setEditable(true);
        }
        else
        {
             jTextFieldSearch.setEditable(false);
        }
    }//GEN-LAST:event_jTextFieldSearchKeyPressed
public class Function
{
       Connection con=null;
       ResultSet rs=null;
       PreparedStatement ps=null;

        public ResultSet find(String s)
        {
                try
                {
                        con = DriverManager.getConnection("jdbc:mysql:///ams","root","");  
                         ps=con.prepareStatement("select * from employee where Employee_Name = ?");
                         ps.setString(1,s);
                        rs=ps.executeQuery();
                }
                catch(Exception ex)
                {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                return rs;
        }
        
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
