/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline.system;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.*;
import java.sql.*;
import java.awt.event.*;
/**
 *
 * @author BHAVESH
 */
public class TicketCancellation extends javax.swing.JFrame {

    /**
     * Creates new form TicketCancellation
     */
    public TicketCancellation() {
        initComponents();
        autoId(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldFare = new javax.swing.JTextField();
        jTextFieldAadhar = new javax.swing.JTextField();
        jTextFieldMob = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCName = new javax.swing.JTextField();
        jTextFieldDestination = new javax.swing.JTextField();
        jTextFieldSource = new javax.swing.JTextField();
        jTextFieldFName = new javax.swing.JTextField();
        jButtoncancelticket = new javax.swing.JButton();
        jButtoncancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPassport = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1450, 750));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("Ticket Cancellation");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 20, 540, 60);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("Passport No              :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 520, 310, 40);

        jTextFieldCID.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldCID.setEnabled(false);
        getContentPane().add(jTextFieldCID);
        jTextFieldCID.setBounds(500, 150, 240, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setText("Cancellation ID   :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 140, 260, 40);

        jTextFieldSearch.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldSearch);
        jTextFieldSearch.setBounds(500, 230, 240, 30);

        jButtonSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\Search-removebg-preview (3).png")); // NOI18N
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jButtonSearch.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtonSearchPropertyChange(evt);
            }
        });
        getContentPane().add(jButtonSearch);
        jButtonSearch.setBounds(760, 220, 60, 60);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setText("Enter Customer Name to search   :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 220, 550, 40);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setText("Fare                     :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(610, 470, 310, 40);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setText("Customer Mob_No    :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 370, 340, 40);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setText("Address                     :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 420, 310, 40);

        jTextFieldAddress.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldAddress.setEnabled(false);
        getContentPane().add(jTextFieldAddress);
        jTextFieldAddress.setBounds(330, 430, 240, 30);

        jTextFieldFare.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldFare.setEnabled(false);
        getContentPane().add(jTextFieldFare);
        jTextFieldFare.setBounds(870, 480, 240, 30);

        jTextFieldAadhar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldAadhar.setEnabled(false);
        getContentPane().add(jTextFieldAadhar);
        jTextFieldAadhar.setBounds(330, 480, 240, 30);

        jTextFieldMob.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldMob.setEnabled(false);
        getContentPane().add(jTextFieldMob);
        jTextFieldMob.setBounds(330, 380, 240, 30);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel9.setText("Customer Name        :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 320, 310, 40);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setText("Flight Name        :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(610, 320, 310, 40);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel11.setText("Source                 :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(610, 380, 310, 30);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel12.setText("Destination         :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(610, 420, 310, 40);

        jTextFieldCName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldCName.setEnabled(false);
        getContentPane().add(jTextFieldCName);
        jTextFieldCName.setBounds(330, 330, 240, 30);

        jTextFieldDestination.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldDestination.setEnabled(false);
        getContentPane().add(jTextFieldDestination);
        jTextFieldDestination.setBounds(870, 430, 240, 30);

        jTextFieldSource.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldSource.setEnabled(false);
        getContentPane().add(jTextFieldSource);
        jTextFieldSource.setBounds(870, 380, 240, 30);

        jTextFieldFName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldFName.setEnabled(false);
        getContentPane().add(jTextFieldFName);
        jTextFieldFName.setBounds(870, 330, 240, 30);

        jButtoncancelticket.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jButtoncancelticket.setText("Cancel Ticket");
        jButtoncancelticket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtoncancelticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelticketActionPerformed(evt);
            }
        });
        jButtoncancelticket.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtoncancelticketPropertyChange(evt);
            }
        });
        getContentPane().add(jButtoncancelticket);
        jButtoncancelticket.setBounds(240, 580, 340, 47);

        jButtoncancel.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jButtoncancel.setText("Cancel");
        jButtoncancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelActionPerformed(evt);
            }
        });
        jButtoncancel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButtoncancelPropertyChange(evt);
            }
        });
        getContentPane().add(jButtoncancel);
        jButtoncancel.setBounds(680, 580, 200, 47);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel13.setText("Aadhar Card No        :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 470, 310, 40);

        jTextFieldPassport.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldPassport.setEnabled(false);
        getContentPane().add(jTextFieldPassport);
        jTextFieldPassport.setBounds(330, 530, 240, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHAVESH\\Documents\\NetBeansProjects\\Airline System\\Icon\\MainPage.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -210, 1520, 1130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed

       if(jTextFieldSearch.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter Employee Name","swing Tester",JOptionPane.WARNING_MESSAGE);
        }

        Function f=new Function();
        ResultSet rs=null;

        rs=f.find(jTextFieldSearch.getText());
        try
        {
            
            //Fetch Data From TicketBooking Table
            if(rs.next())
            
                {
                    jTextFieldCName.setText(rs.getString("Customer_Name"));
                    jTextFieldMob.setText(rs.getString("Mobile_No"));
                    jTextFieldAddress.setText(rs.getString("Address"));
                    jTextFieldAadhar.setText(rs.getString("Aadhar_Card"));
                    jTextFieldFName.setText(rs.getString("Flight_Name"));
                    jTextFieldSource.setText(rs.getString("Source"));
                    jTextFieldDestination.setText(rs.getString("Destination"));
                    jTextFieldFare.setText(rs.getString("Fare"));
                    jTextFieldPassport.setText(rs.getString("Passport_No"));
                } 
            
            else
            {
                JOptionPane.showMessageDialog(null, "Data Not Found");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonSearchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtonSearchPropertyChange
        jButtonSearch.setOpaque(false);
        jButtonSearch.setContentAreaFilled(false);
      
    }//GEN-LAST:event_jButtonSearchPropertyChange

    private void jButtoncancelticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelticketActionPerformed
            try
            {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql:///ams","root",""); 

                    String sql="insert into cancellation values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement pstmt=con.prepareStatement(sql);
                    pstmt.setInt(1,Integer.parseInt(jTextFieldCID.getText()));
                    pstmt.setString(2,jTextFieldCName.getText());
                    pstmt.setString(3,jTextFieldMob.getText());
                    pstmt.setString(4,jTextFieldAddress.getText());
                    pstmt.setString(5,jTextFieldAadhar.getText());
                    pstmt.setString(6,jTextFieldFName.getText());
                    pstmt.setString(7,jTextFieldSource.getText());
                    pstmt.setString(8,jTextFieldDestination.getText());
                    pstmt.setString(9,jTextFieldFare.getText());
                    pstmt.setString(10,jTextFieldPassport.getText());
              
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Ticket Cancel Successfully.........!!!");
                    con.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }       
    }//GEN-LAST:event_jButtoncancelticketActionPerformed

    private void jButtoncancelticketPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtoncancelticketPropertyChange
        jButtoncancelticket.setOpaque(false);
        jButtoncancelticket.setContentAreaFilled(false);
      
    }//GEN-LAST:event_jButtoncancelticketPropertyChange

    private void jButtoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelActionPerformed
       EmployeeMenu1 a=new EmployeeMenu1();
       a.setVisible(true);
    }//GEN-LAST:event_jButtoncancelActionPerformed

    private void jButtoncancelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButtoncancelPropertyChange
        jButtoncancel.setOpaque(false);
        jButtoncancel.setContentAreaFilled(false);
       
    }//GEN-LAST:event_jButtoncancelPropertyChange
//Validation for search customer Name
    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        char c= evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
               jTextFieldSearch.setEditable(true);
        }
        else
        {
             jTextFieldSearch.setEditable(false);
        }
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed
private void autoId() 
{ 
       try 
       {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql:///ams","root",""); 

             String sql="SELECT Cancellation_ID FROM cancellation ORDER BY Cancellation_ID DESC LIMIT 1";
             PreparedStatement pst=con.prepareStatement(sql); 
             ResultSet rs=pst.executeQuery(); 
             if(rs.next()) 
             { 
                 String bid=rs.getString("Cancellation_ID"); 
                 int n=Integer.parseInt(bid); 
                 n++;
                 String snum=Integer.toString(n);
                 jTextFieldCID.setText(snum); 
             }
             else 
            {
                jTextFieldCID.setText("1"); 
            } 
       } 
      catch (Exception e)
       { 
            JOptionPane.showMessageDialog(null, e);
       }
 }
public class Function
{
       Connection con=null;
       ResultSet rs=null;
       PreparedStatement ps=null;

        public ResultSet find(String s)
        {
                try
                {
                        con = DriverManager.getConnection("jdbc:mysql:///ams","root","");  
                         ps=con.prepareStatement("select * from ticketbooking where Customer_Name = ?");
                         ps.setString(1,s);
                        rs=ps.executeQuery();
                }
                catch(Exception ex)
                {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                return rs;
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketCancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketCancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketCancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketCancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketCancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtoncancel;
    private javax.swing.JButton jButtoncancelticket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jTextFieldAadhar;
    public static javax.swing.JTextField jTextFieldAddress;
    public static javax.swing.JTextField jTextFieldCID;
    public static javax.swing.JTextField jTextFieldCName;
    public static javax.swing.JTextField jTextFieldDestination;
    public static javax.swing.JTextField jTextFieldFName;
    public static javax.swing.JTextField jTextFieldFare;
    public static javax.swing.JTextField jTextFieldMob;
    public static javax.swing.JTextField jTextFieldPassport;
    public static javax.swing.JTextField jTextFieldSearch;
    public static javax.swing.JTextField jTextFieldSource;
    // End of variables declaration//GEN-END:variables
}
